### PR TITLE
Rylie deap 0

### PR DESCRIPTION
**Pull request by RylieWeaver**
Changes to deap workflow, implementation, and explanation. + OneD

### CODE REVIEW

**Comment by rajeeja** [comment]
Point it to develop instead of master

**Comment by RylieWeaver** [comment]
> Point it to develop instead of master

Ok, I believe I've done so now.

**Comment by j-woz** [comment]
I think we need to start over here.  I would create a new clone of Supervisor, make sure you are up-to-date on branch develop, copy your changed files in there, and post that.  I will stop making changes today so you won't have to worry about any new conflicts.

**Comment by RylieWeaver** [comment]
Ok, I can do that.

**Comment by j-woz** [comment]
If you have small doc fixes or cleanups, start with those.  Small PRs are best.

**Comment by RylieWeaver** [comment]
Ok, I've cloned and made a new pull request, this time with just changes to the README file to start. It says 'All Checks Failed' but I believe this is just related to style and involves code files that I didn't change, so I left as is.

**Pull request closed without merging**
