### PR TITLE
OneD Jupyter Notebook

### PR DESCRIPTION
**Pull request by RylieWeaver**
Add OneD DEAP example with jupyter notebook

### CODE REVIEW

**Comment by rajeeja** [comment]
move this to models/oneD

**Comment by RylieWeaver** [comment]
> move this to models/oneD

Done

**Comment by rajeeja** [comment]
It'd good if you also add a plot of the function indicating the local and global minima(s) with values in comments.

**Comment by RylieWeaver** [comment]
Sounds good just added.

**Pull request merged**
